# Lesson 1: Computational Project Organization

## 2 Oct 2023

***Consider which steps only need to be configured once versus which have to be repeated for every project. If there were steps you found counter-intuitive or confusing today, make a note of why you did them or how you figured them out.***

### Step 1: Create an RStudio Project + Git Repository

#### These steps should be repeated for every new project.

New RStudio Project:

-   Open RStudio, File \> New Project \> New Directory \> New Project

-   Navigate to the parent directory in which you'd like your repo to live. (for Salma this is usually in the "GitHub" folder in your "Documents" )

-   Click create project

-   Weeeee you made a project with a git repo - go girl go!

### Step 2: Create a GitHub repository

-   Make a [GitHub](http://github.com/) account - *only need to do this step once*

-   `install.packages("usethis")` *only need to do this step once*

-   Check to make sure that git is configured properly to communicate with your GitHub account - confusing I know but programmers are the worst with nomenclature...

    -   In the **TERMINAL** (not console) run `git config --list`. Check to make sure that your user.name and user.email are the same (your user.name won't have the @email.com).

    -   If you need to change them: `usethis::use_git_config(user.name = "YOURNAME", user.email = "YOUREMAIL")` *only need to do this step once*

-   Make a Personal Access Token (PAT) to make sure that your work is secure and that Joe Schmoes on the interwebs can't commandeer your work. *You* *only need to do this step once*

    -   In the **CONSOLE** run `usethis::create_github_token()`

    -   This will take you to a web browser session with GitHub.

    -   Call the Token `RSTUDIO` and set the expiration to `90 days` vs. 30

    -   Click `Generate Token`

    -   Copy and paste the long text with a green check mark next to it.

    -   In RStudio **CONSOLE** run `gitcreds::gitcreds_set()`

    -   You'll be prompted for a password/token; paste the string of text you copied a couple steps above.

YAY! You have github set up for git repos!

Creating your GitHub project repo, in the console run:

-   `usethis::use_git()`

-   Commit any files needed

-   `usethis::git_default_branch_rename()`

-   `usethis::use_github()`

-   Now check your repo in the browser! Go girl go!

### Step 3: Set up folder structure

These folders are created for every new project - internalize this and you will never have decision fatigue again!

-   `data` contains all input data (and metadata) used in the analysis.

-   `paper` contains the manuscript.

-   `figs` contains figures generated by the analysis.

-   `output` contains any type of intermediate or output files (e.g. simulation outputs, models, processed datasets, etc.). You might separate this and also have a cleaned-data folder.

-   `R` contains R scripts with function definitions.

-   `reports` contains Quarto documents that describe the analysis or report on results.

-   `docs` contains the rendered versions of the reports.

-   `scratch` contains early prototypes and other code I don't fully understand yet.

-   and any other relevant folders that you may need!

-   `{r AUTOMATE project setup} project_setup <- function() {       dir.create("data")       dir.create("reports")       dir.create("docs")       dir.create("R")       file.create("data/README.md")       writeLines("The data directory contains raw/processed data used in class", "data/README.md")       file.create("reports/README.md")       writeLines("The reports directory contains Quarto documents that describe the analysis or report on results.", "reports/README.md")       file.create("docs/README.md")       writeLines("The docs directory contains the rendered versions of the report.",                   "docs/README.md")       file.create("R/README.md")       writeLines("The R directory contains code + notes that I've taken in class",                   "R/README.md")       return("SUCCESS!")     }`

### Step 4: Activate GitHub Pages

This enables github to create a website from you R project repository!

-   In GitHub go to:

    -   Settings \> Pages \> Branch; change to *main*, folder to */docs* \> Save

-   Commit + push changes in R

-   In GitHub: Actions tab \> once your job is green click and check it out!
